#' Calculate contrasts between marginal predictions for predictor values
#'
#' @param marginal_preds Object of class \code{marginalPreds} generated by \code{marginal_predictions}.
#' @param var Character string of the name of the predictor for which to calculate contrasts
#' @param verbose Logical indicating whether additional information should be printed
#'
#' @author Jason Grafmiller
#'
#' @details Add details here
#'
#' @return A \code{data.frame}.
#' \describe{
#' }
#'
#' @references Add references here
#' @export
#'
#' @examples
#' \dontrun{}
marginal_contrasts <- function(marginal_preds, var, verbose = FALSE){
  require(data.table) # use data.table because the results can be very large

  if(class(marginal_preds) != "marginalPreds") stop(paste(marginal_preds, 'is not of class "marginalPreds"'))

  mar_table <- marginal_preds$predictions

  if(!is.data.table(mar_table)) mar_table <- as.data.table(mar_table)

  levs <- sort(as.character(unique(mar_table[, get(var)])))

  peripheral_vars <- names(mar_table)[!names(mar_table) %in% c(var, "pred_prob", "Freq", "tree")]

  if(verbose) message("Treating the following predictors as peripheral:\n", paste(peripheral_vars, collapse = ", "))

  f <- as.formula(paste(paste(c(peripheral_vars, "tree"), collapse = " + "), var, sep = " ~ "))

  wide_dt <- dcast(mar_table, f, value.var = "pred_prob")

  if(length(levs) > 2){
    # For factors with more than 2 levels we calculate all 2-way contrasts, so
    # for n factor levels we will have n!/(2(n - 2)!) contrasts
    combs <- combn(seq_along(levs), 2)
    comb_dt <- apply(combs, 2, function(c) wide_dt[, get(levs[c[1]])] - wide_dt[, get(levs[c[2]])]) |>
      as.data.table()
    names(comb_dt) <- apply(combs, 2, function(c) paste("contrast", levs[c[1]], levs[c[2]], sep = '_'))
    wide_dt <- cbind(wide_dt, comb_dt)
    # average by peripheral predictors
    contrast_cols <- names(wide_dt)[grepl("contrast",names(wide_dt))]

    avg_contrast_df <- wide_dt[, lapply(.SD, mean), by = peripheral_vars, .SDcols = contrast_cols] |>
      as.data.frame()

  } else {
    wide_dt$contrast <- wide_dt[, get(levs[2])] - wide_dt[, get(levs[1])]
    message("Contrasts represent difference in predicted probability: ", levs[2], " - ", levs[1])
    avg_contrast_df <- wide_dt[, .(mean = mean(contrast)), by = peripheral_vars] |>
      as.data.frame()
    names(avg_contrast_df)[names(avg_contrast_df) == "mean"] <- paste("mean", var, "contrast", sep = "_")
  }

  return(avg_contrast_df)
}

